//
//  ArticleDetailModels.swift
//  NYTimesArticles
//
//  Created by Sharon Varghese on 30/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ArticleDetail
{
    // MARK: Use cases
    
    enum ArticleItem
    {
      struct Request
      {
      }
      struct Response
      {
          let article: Article?
      }
      struct ViewModel
      {
          struct ArticleTitleModel {
              let title: String?
          }
          struct ArticleImageModel {
              let imageURLString: String?
          }
          struct ArticleAuthorAndDateModel {
              let author: String?
              let date: String?
          }
          struct ArticleDescriptionModel {
              let description: String?
          }
          let article: Article?
      }
    }
}
