//
//  ArticleDetailViewController.swift
//  NYTimesArticles
//
//  Created by Sharon Varghese on 30/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailDisplayLogic: AnyObject
{
  
    func displayArticle(detail: [Any])
}

class ArticleDetailViewController: UIViewController, ArticleDetailDisplayLogic
{
    // MARK: Object lifecycle
    var interactor: ArticleDetailBusinessLogic?
    var router: (NSObjectProtocol & ArticleDetailRoutingLogic & ArticleDetailDataPassing)?
    var articleDetail: [Any]?
    
    // MARK: @IBOutlet
    @IBOutlet var tableView: UITableView!
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ArticleDetailInteractor()
        let presenter = ArticleDetailPresenter()
        let router = ArticleDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        prepareNavigationBar()
        prepareTableView()
        showArticle()
    }
    
    // MARK: Set up Views
    
    func prepareNavigationBar() {
        navigationItem.largeTitleDisplayMode = .never
    }
    
    func prepareTableView()  {
        tableView.register(UINib(nibName: "ArticleDetailTitleTableViewCell", bundle: nil), forCellReuseIdentifier: ArticleDetailTitleTableViewCell.reuseIdentifier)
        tableView.register(UINib(nibName: "ArticleDetailImageTableViewCell", bundle: nil), forCellReuseIdentifier: ArticleDetailImageTableViewCell.reuseIdentifier)
        tableView.register(UINib(nibName: "ArticleDetailDateTableViewCell", bundle: nil), forCellReuseIdentifier: ArticleDetailDateTableViewCell.reuseIdentifier)
        tableView.register(UINib(nibName: "ArticleDetailDescriptionTableViewCell", bundle: nil), forCellReuseIdentifier: ArticleDetailDescriptionTableViewCell.reuseIdentifier)
        tableView.estimatedRowHeight = 150
    }
    
    func showArticle()
    {
        interactor?.showSelectedArticle()
    }
    
    func displayArticle(detail: [Any]) {
        self.articleDetail = detail
        tableView.reloadData()
    }
}
// MARK: UITableViewDelegate

extension ArticleDetailViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
// MARK: UITableViewDataSource

extension ArticleDetailViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.articleDetail?.count ?? 0
        
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let detail = self.articleDetail?[indexPath.row]
        switch detail {
        case is ArticleDetail.ArticleItem.ViewModel.ArticleTitleModel:
            if let cellData = detail as? ArticleDetail.ArticleItem.ViewModel.ArticleTitleModel {
                let cell = tableView.dequeueReusableCell(withIdentifier: ArticleDetailTitleTableViewCell.reuseIdentifier, for: indexPath) as! ArticleDetailTitleTableViewCell
                cell.data = cellData
                return cell
            }
        case is ArticleDetail.ArticleItem.ViewModel.ArticleImageModel:
            if let cellData = detail as? ArticleDetail.ArticleItem.ViewModel.ArticleImageModel {
                let cell = tableView.dequeueReusableCell(withIdentifier: ArticleDetailImageTableViewCell.reuseIdentifier, for: indexPath) as! ArticleDetailImageTableViewCell
                cell.data = cellData
                return cell
            }
        case is ArticleDetail.ArticleItem.ViewModel.ArticleAuthorAndDateModel:
            if let cellData = detail as? ArticleDetail.ArticleItem.ViewModel.ArticleAuthorAndDateModel {
                let cell = tableView.dequeueReusableCell(withIdentifier: ArticleDetailDateTableViewCell.reuseIdentifier, for: indexPath) as! ArticleDetailDateTableViewCell
                cell.data = cellData
                return cell
            }
        case is ArticleDetail.ArticleItem.ViewModel.ArticleDescriptionModel:
            if let cellData = detail as? ArticleDetail.ArticleItem.ViewModel.ArticleDescriptionModel {
                let cell = tableView.dequeueReusableCell(withIdentifier: ArticleDetailDescriptionTableViewCell.reuseIdentifier, for: indexPath) as! ArticleDetailDescriptionTableViewCell
                cell.data = cellData
                return cell
        }
        default:
            return UITableViewCell()
        }
        return UITableViewCell()
    }
    
    
    
}
