//
//  ArticleListPresenter.swift
//  NYTimesArticles
//
//  Created by Sharon Varghese on 29/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleListPresentationLogic
{
    func presentArticleList(response: ArticleList.FetchArticleList.Response)
}

class ArticleListPresenter: ArticleListPresentationLogic
{
  weak var viewController: ArticleListDisplayLogic?
    // MARK: Present Article List
    
    func presentArticleList(response: ArticleList.FetchArticleList.Response)
      {
          let viewModel = ArticleList.FetchArticleList.ViewModel(articles: response.articles, error: response.error)
          viewController?.displayArticleList(viewModel: viewModel)
      }
}
