//
//  ArticleListWorker.swift
//  NYTimesArticles
//
//  Created by Sharon Varghese on 29/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ArticleListWorker
{
    func fetchArticles(numberOfDays: Int, completion: @escaping (Result<[Article]?, ErrorInfo>)->()) {
        
        let params = ["api-key" : Secrets.nytAPIKey]
        APIManager.shared().call(type: EndPointItem.viewed(numberOfDays), params: params) { (result: Swift.Result<ArticleNetworkModel, ErrorInfo>) in
            switch result {
            case .success(let response):
                completion(.success(response.results))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
